create or replace TABLE SALESDATABASE.SALES.CUSTOMERS (
	COUNTRY VARCHAR(6),
	CUSTOMERID NUMBER(1,0) NOT NULL,
	EMAIL VARCHAR(4),
	FIRSTNAME VARCHAR(2),
	JOINDATE DATE,
	LASTNAME VARCHAR(3),
	PHONENUMBER VARCHAR(15),
	primary key (CUSTOMERID)
);


create or replace TABLE SALESDATABASE.SALES.ORDERS (
	ORDERID NUMBER(10,0) NOT NULL,
	CUSTOMERID NUMBER(1,0) NOT NULL,
	ORDERDATE DATE,
	TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
	STATUS VARCHAR(20) DEFAULT 'Pending',
	UPDATED_AT DATE,
	primary key (ORDERID),
	foreign key (CUSTOMERID) references SALESDATABASE.SALES.CUSTOMERS(CUSTOMERID)
);


create or replace TABLE SALESDATABASE.SALES.PRODUCT (
	PRODUCTID NUMBER(5,0) NOT NULL,
	PRODUCTNAME VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(30),
	PRICE NUMBER(10,2) NOT NULL,
	STOCK_QUANTITY NUMBER(10,0) NOT NULL,
	SUPPLIERID NUMBER(5,0),
	CREATED_AT DATE,
	UPDATED_AT DATE,
	primary key (PRODUCTID)
);